- name: Add worker nodes to inventory
  debug:
    msg: "{{ item }}"
  with_items: "{{ worker_ips }}"

- name: Add worker nodes to inventory
  add_host:
    name: "{{ item }}"
    ansible_user: nutanix
    groups: workers
    become: yes
    ansible_python_interpreter: /usr/bin/python
    ansible_connection: ssh
    ansible_ssh_private_key_file: "{{ ssh_private_key_path }}"
  with_items: "{{ worker_ips }}"
