---
- hosts: localhost
  collections:
    - yst.ntnx
  tasks:
    - name: Karbon GET SSH Certificates
      ntnx_karbon_ssh_certificates:
        name: "{{ cluster_name }}"
        state: present
        pc_host: "{{ pc_host }}"
        pc_username: "{{ pc_username }}"
        pc_password: "{{ pc_password }}"
        ssh_certificates_download_path: "./KARBON-{{ cluster_name }}"
        ssl_verify: False
